src/carts/urls.py
from django.conf.urls import url


from .views import (
    # product_list,
    cart_view,
 
    cart_update,	
    test
)


#app_name = 'products'

urlpatterns = [
 

 url(r'^$', cart_view, name = 'home'),
 url(r'^update/$', cart_update, name = 'update'),
 url(r'^test/$', test, name = 'test'),
 
 
]

src/ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from carts.views import cart_view


#from django.urls import path
from .views import (home_page, contact_page, user_info, about_page, 
login_page, register_page, fet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^bootstrap/', TemplateView.as_view(template_name = 'bootstrap/example.html')),
    url(r'^$', home_page, name ='home'),
    url(r'^contact$', contact_page, name = 'contact'),
    url(r'^about$', about_page),
    url(r'^login$', login_page, name = 'login'),
   # url(r'^cart$', cart_view, name = 'cart'),
    url(r'^register$', register_page, name = 'register'),
    url(r'^products/', include('products.urls', namespace = 'product')),
    url(r'^cart/', include('carts.urls', namespace = 'cart')),
    url(r'^search/', include('search.urls', namespace = 'search')),
    url(r'^order/', include('order.urls', namespace = 'order')),
    url(r'^userinfo/', user_info, name = 'userinfo'),
    url(r'^fet/', fet, name = 'fet'),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/order/urls.py
from django.conf.urls import url


from .views import (
   order_view,
   order_summary,
   order_pay,
   saved_orders,
   single_order,
   order_list

)


#app_name = 'products'

urlpatterns = [
 url(r'^$', order_view, name = 'home'),
  url(r'^summary$', order_summary, name = 'summary'),
  url(r'^pay$', order_pay, name = 'pay'),
  url(r'^savedorders$', saved_orders, name = 'saved'),
  url(r'^single$', single_order, name = 'single'),
  url(r'^list$', order_list, name = 'list'),

 
]

src/templates/base/css.html
 {% load static %}

 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

 <link rel="stylesheet" href="{% static 'css/main.css' %}">
            
 

src/templates/base/js.html
 <!-- Optional JavaScript -->
		    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
{% load static %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" crossorigin="anonymous"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

src/templates/base/nav.html
{% load static %}
{% load update_prod %}

{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'product:list' as product_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}
{% url 'order:saved' as save_order %}



<script>
function myFunction() {
  alert("Hello! I am an alert box!");
}
</script>

<link rel="stylesheet" href="{% static 'css/nav.css' %}">


<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
 <div class = 'container'>
  <a class="navbar-brand" href="{{ home_url }}">
 
        <img src='{% static "img/vlogo.png" %}' width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
        Planet</a>
<!--{%if brand%}{{brand}}{%else%} V2-Shop m{%endif%}</a>-->
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">
  <li class="nav-item {% if request.path == home_url %}active{%endif%}">
    <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
  </li>
  <li class="nav-item {% if request.path == contact_url %}active{%endif%}">
    <a class="nav-link" href="{% url 'contact' %}">Contact</a>
  </li>
  <li class="nav-item {% if request.path == product_url %}active{%endif%}">
    <a class="nav-link" href="{% url 'product:list' %}">Product</a>
  </li>
  {% if request.user.is_authenticated %}
  <li class="nav-item {% if request.path == login_url %}active{%endif%}">
   <a class="nav-link" href="{% url 'login' %}">logout</a>
  </li>
  {% else %}
  <li class="nav-item {% if request.path == login_url %}active{%endif%}">
    <a class="nav-link" href="{% url 'login' %}">login</a>
  </li>

  <li class="nav-item {% if request.path == register_url %}active{%endif%}">
    <a class="nav-link" href="{% url 'register' %}">register</a>
  </li>
  {% endif %}
  <li class="nav-item dropdown">
          
           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown link
            </a>
           <div class="dropdown-menu dropdown-menu-left" id = "drop"aria-labelledby="navbarDropdownMenuLink">
           <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"> -->
            <a class="dropdown-item" href="{{cart_url}}" >cart</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Link</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">New</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{save_order}}">orders</a>
            
            </div>
            </li>
</ul>
{%include 'search/snippets/search_form.html' %}
 
  <a href="{% url 'cart:home' %}" style = 'margin-left: 4px; padding-left: 8px;'>
    <div class = 'container' style= 'position:relative; margin-bottom: 40px'>
    
    <div style="position:absolute; "><img src='{% static "img/cart2.jpg" %}' alt="" width="45" height="45"></div>
    <div style="position:absolute; margin-left: 14px; margin-bottom: 8px;padding-bottom:5px; color:black; font-weight: bolder">{% if request.user.is_authenticated %}{{count|prod_add:user}} {% endif %}</div>
  </div>

     </a>


</div>
</div>
</nav>