src/carts/urls.py
from django.conf.urls import url


from .views import (
    # product_list,
    cart_view,
 
    cart_update,	
    test
)


#app_name = 'products'

urlpatterns = [
 

 url(r'^$', cart_view, name = 'home'),
 url(r'^update/$', cart_update, name = 'update'),
 url(r'^test/$', test, name = 'test'),
 
 
]

src/ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from carts.views import cart_view


#from django.urls import path
from .views import (home_page, contact_page, user_info, about_page, 
login_page, register_page, fet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^bootstrap/', TemplateView.as_view(template_name = 'bootstrap/example.html')),
    url(r'^$', home_page, name ='home'),
    url(r'^contact$', contact_page, name = 'contact'),
    url(r'^about$', about_page),
    url(r'^login$', login_page, name = 'login'),
   # url(r'^cart$', cart_view, name = 'cart'),
    url(r'^register$', register_page, name = 'register'),
    url(r'^products/', include('products.urls', namespace = 'product')),
    url(r'^cart/', include('carts.urls', namespace = 'cart')),
    url(r'^search/', include('search.urls', namespace = 'search')),
    url(r'^order/', include('order.urls', namespace = 'order')),
    url(r'^userinfo/', user_info, name = 'userinfo'),
    url(r'^fet/', fet, name = 'fet'),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/order/urls.py
from django.conf.urls import url


from .views import (
   order_view,
   order_summary,
   order_pay,
   saved_orders,
   single_order,
   order_list

)


#app_name = 'products'

urlpatterns = [
 url(r'^$', order_view, name = 'home'),
  url(r'^summary$', order_summary, name = 'summary'),
  url(r'^pay$', order_pay, name = 'pay'),
  url(r'^savedorders$', saved_orders, name = 'saved'),
  url(r'^single$', single_order, name = 'single'),
  url(r'^list$', order_list, name = 'list'),

 
]

src/order/models.py
from django.db import models
from products.models import Product

# Create your models here.


class ProductPurchase:
    
    prodlist = {}

    # def __init__(self, prod):
    #     self.__prodlist = prod
    
    def set_prod(self, prodnew):
        
        self.prodlist = prodnew

    def get_prod(self):
        
        return self.prodlist


    




# class ProductPurchase:
#     global prod_list 
#     prod_list = {}
#     def set_product_purchase(self,context):
#         print(context['product_list'])
#         prod_list = context['product_list']
#         print(prod_list)
#     def get_product_purchase(self):
#         print(prod_list)
#         return prod_list

# class ProductPurchase:
#     def set_product_purchase(self,request):
#         print('i am here')
        

#     def get_product_purchase(self):
#         return self.prod_list

class OrderManager(models.Manager):
    prod_list = {} 
    context = {}
    def create_order(self,user):
        order = self.create(user=user)
        return order

    


        # prod_list = context['product_list']
        # for product in self.context['product_list']:
        #   print(product.title)

   


class Order(models.Model):
    
    user = models.CharField(max_length = 100)
    products = models.ManyToManyField(Product, blank= True)
    address  = models.CharField(max_length = 500)
    total = models.DecimalField(default = 0.00, max_digits= 100 , decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add = True)
    phone = models.CharField(max_length = 20)


    objects = OrderManager()

src/order/forms.py
from django import forms
from .models import Order




class SaveInDB(forms.ModelForm):
    class Meta:
      model= Order
      fields = [
        'user',
        'products',
        'total',
        'address',
        'timestamp',
        'phone',
      ]

src/order/views.py
from django.shortcuts import render
from carts.models import Cart
from .models import Order
from .models import Product
from .models import ProductPurchase
from userdetails.models import UserInfo

# Create your views here.

   

def order_view(request):
    print(request.GET)
    return render(request, 'order/order_details.html', {})

def single_order(request):
    print(request.POST)
    prod_id = request.POST.get('product_id')
    global prod_list
    prod_list = Product.objects.none()
    global single_prod
    #context['item']  =  request.POST.get('product')
    #context['total']  = context['item'].price
    single_prod = Product.objects.get(id=prod_id)
    
    context = {
     'item' : single_prod,
     'total' : single_prod.price
    }
    return render(request, 'order/order_summary.html', context)

def order_summary(request):
    print(request.POST)
    id = request.POST.get('cart')
    username = request.user.username
    print(username)

    qs = UserInfo.objects.filter(user= username)
    #print(qs)
    if qs.exists():
     address = str(qs.first().address)
    else:
     address = 'enter address'
    print('printing')
    print(address)

    obj = Cart.objects.get(id=id)
    product_list = obj.products.all()
    total = obj.total
    print(total)
    
    # for product in product_list:
    #   print(product.title)

    context = {
        'product_list': product_list,
        'total': total,
        'address': address

    }
    global prod_list
    prod_list = context['product_list']
    # prods = context['product_list']
    # a = ProductPurchase()
    # b = ProductPurchase()
    # print('before')
    # ProductPurchase.get_prod()
    # ProductPurchase.set_prod(prods)
    # print('after')
    # ProductPurchase.get_prod()
    #a.set_prod(context)
    # print('before')
    # print(a.get_prod())
    # print(b.get_prod())
    # a.set_prod(prods)
    # print('after')
    # print(a.get_prod())
    # print(b.get_prod())
    #ProductPurchase.prodlist = context['product_list']
    #a.set_product_purchase(context)
    #a.set_prodlist(context['product_list'])
    return render(request, 'order/order_summary.html', context)

def order_pay(request):
    #prod_list = request.POST.get('product_list')
    #prod_list2 = Product(prod_list)
    # print(prod_list)
    # print(Product.objects.all())
    # print(request.user)
    
    new_order = Order.objects.create_order(user=str(request.user))
    # b = ProductPurchase()
    # prod_list= ProductPurchase.prodlist
    # prod_list= b.get_prod()
    global prod_list
    global single_prod
    if prod_list.exists() :
        for product in prod_list:
            print('hi')
            print(product)
            new_order.products.add(product)
    else:
        new_order.products.add(single_prod)
    new_order.total = request.POST.get('total')
    new_order.address = request.POST.get('address')
    
    new_order.phone = '03326511974' 

    new_order.save()

    return render(request, 'order/pay.html', {})


def saved_orders(request):
    print(request.POST)
    id = request.POST.get('order_id')
    #orders = Order.objects.filter(user=str(request.user))
    #sorted_order = orders.order_by('-timestamp')
    #print(orders)
    order = Order.objects.get(id=id)
    orders = Order.objects.all().order_by('-timestamp')
    print(id)
    context = {
     'order': order,
     'orders': orders
    }
    return render(request,'order/saved_order.html', context)

def order_list(request):
    orders = Order.objects.filter(user=str(request.user))
    sorted_order = orders.order_by('-timestamp')
    print(orders)
    context = {
     'orders': sorted_order
    }
    return render(request,'order/order_list.html', context)

src/order/templates/order/final_order.html
{% load static %}


{% include 'order/showform.html' %}


<div style = 'padding-bottom: 18px'>

    <h7> Delivery Address </h7>

    <div> {{address}} </div>

    
</div>

<div>
    <button style = 'margin-top:10px; background-color: skyblue; border-style:hidden;border-radius: 3px ; padding-bottom: 4px' id = 'show'>update address</button>
</div>

<div>
    <form method= 'POST' id="showform" action = "{% url 'order:pay' %}" class = 'form'>{% csrf_token %} 

      {% if product_list.exists %}
          <input type = 'hidden' name = 'product_list' value = '{{product_list}}'/>
      {% else %}
          <input type = 'hidden' name = 'item' value = '{{item}}'/>
      {% endif %}
      <input type = 'hidden' name = 'total' value = '{{total}}'/>
     

      <div class = 'card'  style = 'width:300px; border-style: hidden; background-color: #e1eaea; font-weight: bolder; text-align: center'>

         House & Street<input type = 'text' style = 'width:300px;'name = 'address' value = {{address}}/>
         City<input type = 'text' style = 'width:300px;'name = 'address' value = {{address}}/>
         State<input type = 'text' style = 'width:300px;'name = 'address' value = {{address}}/>
         Pin<input type = 'text' style = 'width:300px;'name = 'address' value = {{address}}/>
         Country<input type = 'text' style = 'width:300px;'name = 'address' value = {{address}}/>
         </div> 

       <div class = 'card text-right'  style = 'width:300px; border-style: hidden; background-color: #e1eaea; padding-top: 30px;'>      
         <p class = 'card-text'>
           <button type = 'submit' class = 'btn btn-info btn-sm' style = 'width:100px;'>pay</button></p>
       </div>
       

    </form>
</div>

src/order/templates/order/order_details.html
{% load static %}

{% url 'order:summary' as ordersum_url %}




<form method= 'POST' action = "{% url 'order:summary'%}" class = 'form'>{% csrf_token %} 
   <input type = 'hidden' name = 'cart' value = '{{cart}}'/>
   
    <button type = 'submit' class = 'btn btn-info btn-sm' style='margin-top:3px; width:100px; border-style: hidden;'>purchase all</button>

</form>

src/order/templates/order/order_list.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href='{% static "css/bg.css" %}'>
{% endblock %}
{% block content %}

<div class="dropdown dropdown-sm">
  <button class="btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style = 'margin-left: auto; margin-right:auto; background-color: #c2d6d6'>
    View Orders
  </button>
  <div class="dropdown-menu dropdown-menu-sm" aria-labelledby="dropdownMenuButton">
    {% for items in orders %}
   <form method= 'POST' action = "{% url 'order:saved' %}" class ='form'>{% csrf_token %} 
    <input type = 'hidden' name = 'order_id' value = '{{items.id}}'/>
    <button class="dropdown-item dropdown-item-sm" type= 'submit' style = 'height:auto;width:200px;'> {{ items.timestamp }}
           
    </button>
    </form>
    
  
    {% endfor %}
  </div>
</div>



{% endblock %}

src/order/templates/order/order_summary.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href='{% static "css/bg.css" %}'>
{% endblock %}



{% block content %}



  <div class = 'container'>
    <div class = 'row'>
      <div class = 'col-6'>
            <table class="table table-sm" style = 'width:300px; background-color: #a3c2c2; border-style: hidden'>
              <thead>
                <tr>
                  <th scope="col"></th>
                  <th scope="col">Product</th>
                  <th scope="col">Price</th>
                  
                </tr>
              </thead>
              <tbody>
                 {% if product_list.exists %}
                  {% for item in product_list %}
                <tr>
                  
                  <th scope="row"></th>
                  <td>{{item.title}}</td>
                  <td>{{item.price}}</td>
                  </tr>
                  {% endfor %}
               
                <tr>
                  <th scope="row"></th>
                  <td>Total</td>
                  <td>{{total}}</td>
                  
                </tr>
                {% else %}
                <tr>
                  <th scope="row"></th>
                  <td>{{item.title}}</td>
                  <td>{{item.price}}</td>
                  
                </tr>
                 <tr>
                  <th scope="row"></th>
                  <td>Total</td>
                  <td>{{total}}</td>
                  
                </tr>
                {% endif %}
                </tr>
                 
              </tbody>
            </table>
        </div>  
        <div class = 'col-6'>
            {% include 'order/final_order.html' %}
        </div>
      </div>
    </div>
{% endblock %}

src/order/templates/order/pay.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href='{% static "css/bg.css" %}'>
{% endblock %}

{% block content %}
<div class = 'container'>
	<div class = 'row'>
		<div class = 'col-6 mx-auto'>
		   <h4> order placed succesfully </h4>
		 </div> 
		 </div> 
         <div class = 'row'>
		 <div class = 'col-6 mx-auto'>
		  <a href= "{% url 'order:list'%}"> <h4>view placed orders </h4></a>
		 </div>
		 </div>
		 </div>

	
</form>
  







{% endblock %}

src/order/templates/order/saved_order.html
{% extends 'base.html' %}


{% load static %}



{% block style %}
<link rel="stylesheet" href='{% static "css/bg.css" %}'>
<link rel="stylesheet" href='{% static "css/placedorder.css" %}'>
{% endblock %}

{% block content %}

<div class="dropdown dropdown-sm">
  <button class="btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style = 'margin-left: auto; margin-right:auto; background-color: #c2d6d6'>
    View Orders
  </button>
  <div class="dropdown-menu dropdown-menu-sm" aria-labelledby="dropdownMenuButton">
    {% for items in orders %}
   <form method= 'POST' action = "{% url 'order:saved' %}" class ='form'>{% csrf_token %} 
    <input type = 'hidden' name = 'order_id' value = '{{items.id}}'/>
    <button class="dropdown-item dropdown-item-sm" type= 'submit' style = 'height:auto;width:200px;'> {{ items.timestamp }}
           
    </button>
    </form>
    
  
    {% endfor %}
  </div>
</div>


 <div class = 'container mx-auto'>
 <div class = 'display'>
  <div> {{order.timestamp}}  </div> 
  <div class="ml-auto" style="width: 200px; padding-right: 10px">
  
  deliver to - {{order.address}}</div>
  <div class="mx-auto" style="width: 200px; font-size: 50; font-weight: bolder;"> V-PLANET</div>
  <div> order nr - {{order.id}}  </div> 
  <div> PRODUCTS</div>
  
  <hr class = 'separator'>
  {% for products in order.products.all %}
 
  <div>{{products.title}} - {{products.price}}</div>
  
  {% endfor %}
  <hr class = 'separator'>
  <div> total - {{order.total}} </div>  
 </div>
</div>
 <div class = 'white'><hr/><div>
 
{% endblock %}

src/order/templates/order/saved_orders.html
{% extends 'base.html' %}


{% load static %}



{% block style %}
<link rel="stylesheet" href='{% static "css/bg.css" %}'>
{% endblock %}

{% block content %}
{% for items in orders %}
 <div class = 'container'>
 <div class = 'display'>
  <div> {{items.timestamp}}  </div> 
  <div class="ml-auto" style="width: 200px; padding-right: 10px">
  
  deliver to - {{items.address}}</div>
  <div class="mx-auto" style="width: 200px; font-size: 50; font-weight: bolder;"> V-PLANET</div>
  <div> order nr - {{items.id}}  </div> 
  <div> PRODUCTS</div>
  
  <hr class = 'separator'>
  {% for products in items.products.all %}
 
  <div>{{products.title}} - {{products.price}}</div>
  
  {% endfor %}
  <hr class = 'separator'>
  <div> total - {{items.total}} </div>  
 </div>
</div>
 <div class = 'white'><hr/><div>
 {% endfor %}
{% endblock %}

src/order/templates/order/showform.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" crossorigin="anonymous"></script>

<script>
$(document).ready(function(){
  $("#showform").hide();

  $("#show").click(function(){
    $("#showform").show();
  });
});
</script>

src/order/templates/order/single_purchase.html
{% load static %}

{% url 'order:single' as ordersingle_url %}




<form method= 'POST' action = "{% url 'order:single'%}" class = 'form'>{% csrf_token %} 
   
   <input type = 'hidden' name = 'product_id' value = '{{product.id}}'/>
    <button type = 'submit' class = 'btn btn-primary btn-sm' style='margin-top:3px; width:100px; border-style: hidden;'>purchase</button>

</form>